//STORE THE LEAST SIGNIFICANT OF NIBBLES OF ACCUMULATOR IN BOTH NIBBLES OF RAM ADDRESS 3CH;
//INPUT A=36H
//OUTPUT 3CH=66H
CSEG AT 0H
	MOV R0,#3CH
	MOV A,#0X36
	MOV @R0,A ; 
	SWAP A ; 63H
	XCHD  A,@R0 ;66H
	MOV @R0,A
	END