//EXCHANGE THE CONTENTS OF THE B REGISTER AND EXTERNAL RAM ADDRESS 02CFH
//B = FFH
//02CFH = 12H
CSEG AT 0H
	MOV B,#0XFF
	//MOV 0X02CF,#0X12 
	MOV DPTR,#0X02CF
	MOV A,#0X12//DATA 
	MOVX @DPTR,A//DATA COPY IN XTERNAL MEMORY ADDRESS 02CFH
	XRL A,B
	XRL B,A
	XRL A,B
	MOVX @DPTR,A
	END