//SUBTRACTION BETWEEN TWO OPERANDS
;A=A-OPERAND-CY
;A=> MINUEND
;OPERAND=> SUBTRAHEND
//PROCESS TO DO:


//1)TAKE TWO'S COMPLEMENT OF SUBTRAHEND
//2)ADD THE 2'S COMPLIMENT RESULT WITH MINUEND
//3)INVERT THE CARRY 
CSEG AT 0H
	MOV A,#0FFH; .....MINUEND
	MOV R1,#0AFH;.......SUBTRAHEND
	SUBB A,R1
	END

//IF THE SUBTRAHEND IS GREATED THAN MINEUND THEN A CARRY WILL BE GENERATED
CSEG AT 0H
	CLR C
	MOV A,#4CH
	MOV R1,#6EH
	SUBB A,R1
	JNC TARGET
	CPL A
	INC A
	TARGET:
			MOV R2,A
	END


//IF THE SUBB IS PERFORMED FOR 2 BYTES OPERATION THEN
;MINEND => 2762H
;SUBTRAHEND => 1296H
;2762H-1296H = 14CCH
CSEG AT 0H
	MOV A,#62H
	SUBB A,#96H
	MOV 31H,A
	MOV A,#27H
	SUBB A,#12H
	MOV 30H,A
	END